
#ifndef MAILIO_EXPORT_H
#define MAILIO_EXPORT_H

#  define MAILIO_EXPORT
#  define MAILIO_NO_EXPORT

#ifndef MAILIO_DEPRECATED
#  define MAILIO_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef MAILIO_DEPRECATED_EXPORT
#  define MAILIO_DEPRECATED_EXPORT MAILIO_EXPORT MAILIO_DEPRECATED
#endif

#ifndef MAILIO_DEPRECATED_NO_EXPORT
#  define MAILIO_DEPRECATED_NO_EXPORT MAILIO_NO_EXPORT MAILIO_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef MAILIO_NO_DEPRECATED
#    define MAILIO_NO_DEPRECATED
#  endif
#endif

#endif /* MAILIO_EXPORT_H */
